# これはTOMLのサンプルファイルです

title = "TOML Example"
title.color = "red"

fruit.name = "banana"     # this is best practice
fruit.color = "yellow"    # same as fruit.color
fruit.flavor = "banana"   # same as fruit.flavor

"quoted_key" = "value"
"key with space" = "value"

f1 = true
f2 = false

zero = 0
x = 1
y = -1
max = 9223372036854775807
min = -9223372036854775808

a = 0xA
b = 0o12
c = 0b1010

[owner]
name = "Tom Preston-Werner"
#dob = 1979-05-27T07:32:00-08:00

[database]
server = "192.168.1.1"
ports = [8001, 8001, 8002]
connection_max = 5000
enabled = true

[servers]

[servers.alpha]
ip = "10.0.0.1"
dc = "eqdc10"

[servers.beta]
ip = "10.0.0.2"
dc = "eqdc10"

[clients]
data = [["gamma", "delta"], [1, 2]]

#hosts = [
#  "alpha",
#  "omega"
#]
#
#str_multiline = """
#Roses are red
#Violets are blue"""